name = "TSSOS"
uuid = "81648402-ffe6-11e9-2394-0de17a9afdad"
authors = ["jwang <wangjie212@amss.ac.cn>"]
version = "1.4.6"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
AbstractPermutations = "36d08e8a-54dd-435f-8c9e-38a475050b11"
COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
MultivariateBases = "be282fd4-ad43-11e9-1d11-8bd9d7e43378"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
PermutationGroups = "8bc5a954-2dfc-11e9-10e6-cd969bffa420"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymbolicWedderburn = "858aa9a9-4c7c-4c62-b466-2421203962a2"

[compat]
MultivariateBases = "0.2.2"
