name = "TSSOS"
uuid = "81648402-ffe6-11e9-2394-0de17a9afdad"
authors = ["jwang <wangjie212@mails.ucas.ac.cn>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
